apt_packages:
  - vim
  - git
  - curl
  - wget
  - htop
  - neofetch
  - unzip
  - gnupg
  - gparted
  - flatpak
  - gnome-software-plugin-flatpak
  - timeshift
  - ca-certificates
  # Developer tools
  - make
  - gcc
  - g++
  - pkg-config
  - python3-dev
  - jq
  - tree
  - shellcheck
  # - docker.io
  # - docker-compose-plugin
  - tmux
  - direnv
  # networking tools
  - net-tools
  - nmap
  - traceroute
  - iputils-ping
  - dnsutils
  # - curlie
  # Security / Privacy Tools
  - gufw                # firewall GUI
  - keepassxc           # password manager
  - seahorse            # GPG key manager
  # Quality of Life
  - xclip               # clipboard for terminal
  - file                # inspect file types
  - fonts-firacode      # coding font
  - numlockx            # auto-enable Num Lock
  - redshift            # screen color temperature
  # Helpers
  # - nvidia-detect      # NVIDIA driver detection
  - linux-headers-amd64
  - dkms
  - firmware-misc-nonfree
  - direnv


flatpak_packages:
  - com.spotify.Client
  - org.gimp.GIMP
  - org.videolan.VLC
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - org.libreoffice.LibreOffice
  # - org.mozilla.Thunderbird
  - com.transmissionbt.Transmission

# TODO replace peronsal_user with your users
personal_user: pernicat

users:
  - pernicat

pipx_packages:
  - uv
  - poetry
  - ruff
  - virtualenv
  - flake8
  - black
  - isort
  - pip-tools
  - mypy
  - bandit
  - autopep8
  - ipython

install_rust: true

nvidia_version: "550.54.14"
# nvidia_distro: "debian12"
# nvidia_arch_ext: "amd64.deb"
