- task: Install APT pre-requisites for AI packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - git
      - wget
      - cmake
      - build-essential
    state: present
    update_cache: yes
  
- task: Install GPU acceleration libraries
  apt:
    name:
      - nvidia-driver-525
      - nvidia-cuda-toolkit
    state: present
    update_cache: yes

# - task: Install torch and torchvision
#   pip:
#     name:
#       - torch==2.0.1+cu118
#       - torchvision==0.15.2+cu118
#       - torchaudio==2.0.2+cu118
#     extra_args: --index-url https://download.pytorch.org/whl/cu118
#     state: present

# - task: Install llama-cpp-python
#   pip:
#     name: llama-cpp-python
#     state: present
#     extra_args: --no-cache-dir