- name: Install APT packages
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes

- name: Install Cinnamon desktop environment
  apt:
    name:
      - task-cinnamon-desktop
    state: present

- name: Ensure Flathub remote is added
  command: >
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub.trustedkeys.gpg

- name: Install Flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop: "{{ flatpak_packages }}"

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install VSCode
  apt:
    name: code
    state: present
    update_cache: yes

- name: Ensure dependencies for pyenv and pipx are installed
  apt:
    name:
      - python3-pip
      - python3-venv
      - pipx
      - gcc
      - make
      - zlib1g-dev
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
    update_cache: yes

- name: Ensure pipx is installed and on PATH
  shell: |
    python3 -m pip install --user pipx
    python3 -m pipx ensurepath
  args:
    executable: /bin/bash
  become: false
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Ensure my personal user exists
  user:
    name: "{{ personal_user }}"
    groups: sudo
    shell: /bin/bash
    create_home: yes
    state: present

- name: Steam requirements
  apt:
    name:
      - libc6:amd64
      - libc6:i386
      - libegl1:amd64
      - libegl1:i386
      - libgbm1:amd64
      - libgbm1:i386
      - libgl1-mesa-dri:amd64
      - libgl1-mesa-dri:i386
      - libgl1:amd64
      - libgl1:i386
      - steam-libs-amd64:amd64
      - steam-libs-i386:i386
    state: present
    update_cache: yes

- name: Ensure Steam is installed
  apt:
    name: steam
    state: present
  ignore_errors: true

- name: Include pyenv setup
  import_tasks: pyenv.yaml

- name: Install CUDA Toolkit
  include_tasks: cuda.yml

- name: Install Docker
  include_tasks: docker.yml
